{
  "type": "record",
  "name": "GPSEvent",
  "namespace": "com.mycompany.events",
  "fields": [
    {
      "name": "gps_event_id",
      "type": "long"
    },
    {
      "name": "id_driver",
      "type": "string"
    },
    {
      "name": "timestamp",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "latitude",
      "type": "double"
    },
    {
      "name": "longitude",
      "type": "double"
    },
    {
      "name": "id_route",
      "type": "long"
    },
    {
      "name": "street",
      "type": "string"
    },
    {
      "name": "house_number",
      "type": "string"
    },
    {
      "name": "priority",
      "type": "int",
      "default": 0
    }
  ]
}
