{
  "type": "record",
  "name": "IncidentEvent",
  "namespace": "tfm.kafka",
  "fields": [
    {
      "name": "id_event",
      "type": "int"
    },
    {
      "name": "id_order",
      "type": "string"
    },
    {
      "name": "id_driver",
      "type": ["null", "string"],
      "default": null
    },
    {
      "name": "type_service",
      "type": "string"
    },
    {
      "name": "previous_status",
      "type": "string"
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "ingestion_time",
      "type": "string"
    }
  ]
}