{
  "type": "record",
  "name": "IncidentEvent",
  "namespace": "com.mycompany.events",
  "fields": [
    {
      "name": "id_incident",
      "type": "string"
    },
    {
      "name": "id_order",
      "type": "string"
    },
    {
      "name": "id_driver",
      "type": ["null", "string"],
      "default": null
    },
    {
      "name": "incident_date",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "incident_reason",
      "type": "string"
    },
    {
      "name": "observations",
      "type": ["null", "string"],
      "default": null
    },
    {
      "name": "resolved",
      "type": "boolean",
      "default": false
    },
    {
      "name": "resolution_date",
      "type": [
        "null",
        {
          "type": "long",
          "logicalType": "timestamp-millis"
        }
      ],
      "default": null
    },
    {
      "name": "resolution_action",
      "type": ["null", "string"],
      "default": null
    }
  ]
}
