{
  "type": "record",
  "name": "OrderEvent",
  "namespace": "com.mycompany.events",
  "fields": [
    {
      "name": "id_event",
      "type": "long"
    },
    {
      "name": "id_order",
      "type": "string"
    },
    {
      "name": "id_driver",
      "type": "string"
    },
    {
      "name": "type_service",
      "type": "string"
    },
    {
      "name": "previous_status",
      "type": "string"
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "timestamp",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    }
  ]
}
