{
  "type": "record",
  "name": "TrafficEvent",
  "namespace": "com.mycompany.events",
  "fields": [
    {
      "name": "fecha_hora",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "idelem",
      "type": "string"
    },
    {
      "name": "descripcion",
      "type": "string"
    },
    {
      "name": "accesoAsociado",
      "type": "string"
    },
    {
      "name": "intensidad",
      "type": "int"
    },
    {
      "name": "ocupacion",
      "type": "int"
    },
    {
      "name": "carga",
      "type": "int"
    },
    {
      "name": "nivelServicio",
      "type": "int"
    },
    {
      "name": "intensidadSat",
      "type": ["null", "int"],
      "default": null
    },
    {
      "name": "error",
      "type": "string"
    },
    {
      "name": "subarea",
      "type": "string"
    },
    {
      "name": "st_x",
      "type": "double"
    },
    {
      "name": "st_y",
      "type": "double"
    }
  ]
}
