{
  "type": "record",
  "name": "WeatherEvent",
  "namespace": "tfm.kafka",
  "fields": [
    {
      "name": "weather_event_id",
      "type": "long"
    },
    {
      "name": "timestamp",
      "type": "string"
    },
    {
      "name": "measurements",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "WeatherMeasurement",
          "fields": [
            {
              "name": "province",
              "type": "string"
            },
            {
              "name": "municipality",
              "type": "string"
            },
            {
              "name": "station",
              "type": "string"
            },
            {
              "name": "station_name",
              "type": "string"
            },
            {
              "name": "year",
              "type": "string"
            },
            {
              "name": "month",
              "type": "string"
            },
            {
              "name": "day",
              "type": "string"
            },
            {
              "name": "hour",
              "type": "int"
            },
            {
              "name": "magnitude_code",
              "type": "string"
            },
            {
              "name": "magnitude",
              "type": "string"
            },
            {
              "name": "value",
              "type": "double"
            },
            {
              "name": "validation",
              "type": "string"
            }
          ]
        }
      }
    },
    {
      "name": "ingestion_time",
      "type": "string"
    }
  ]
}
