{
  "type": "record",
  "name": "WeatherEvent",
  "namespace": "com.mycompany.events",
  "fields": [
    {
      "name": "weather_event_id",
      "type": "long"
    },
    {
      "name": "province",
      "type": "string"
    },
    {
      "name": "municipality",
      "type": "string"
    },
    {
      "name": "station",
      "type": "string"
    },
    {
      "name": "station_name",
      "type": "string"
    },
    {
      "name": "year",
      "type": "int"
    },
    {
      "name": "month",
      "type": "int"
    },
    {
      "name": "day",
      "type": "int"
    },
    {
      "name": "hour",
      "type": "int"
    },
    {
      "name": "timestamp",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "measurements",
      "type": {
        "type": "map",
        "values": {
          "type": "record",
          "name": "WeatherMeasurement",
          "fields": [
            {
              "name": "magnitude_code",
              "type": "string"
            },
            {
              "name": "value",
              "type": ["null", "double"],
              "default": null
            },
            {
              "name": "validation",
              "type": ["null", "string"],
              "default": null
            }
          ]
        }
      }
    }
  ]
}
