from pathlib import Path



# ROOT DEL PROYECTO LOCAL
PROJECT_ROOT = Path(__file__).resolve().parents[2]



# DATOS LOCALES
DATA_ROOT = PROJECT_ROOT / "data"

DATA_ADDRESS = DATA_ROOT / "reference"

HISTORICAL_ROOT = DATA_ROOT / "historical"

SIMULATED_ROOT = DATA_ROOT / "simulated"



# AZURE DATA LAKE STORAGE GEN2
LAKEHOUSE_ROOT = "abfss://tfm@dbtfm.dfs.core.windows.net"

# LANDING
LANDING_ROOT = f"{LAKEHOUSE_ROOT}/landing"

LANDING_ORDERS = f"{LANDING_ROOT}/orders"

LANDING_DRIVERS = f"{LANDING_ROOT}/drivers"

LANDING_ROUTES = f"{LANDING_ROOT}/routes"

LANDING_ORDER_EVENTS = f"{LANDING_ROOT}/order_events"

LANDING_INCIDENT_EVENTS = f"{LANDING_ROOT}/incidents_events"

LANDING_GPS = f"{LANDING_ROOT}/gps_events"

LANDING_WEATHER = f"{LANDING_ROOT}/weather"

LANDING_TRAFFIC = f"{LANDING_ROOT}/traffic"

LANDING_HISTORICAL_ORDERS = f"{LANDING_ROOT}/historical_orders"

LANDING_HISTORICAL_INCIDENTS = f"{LANDING_ROOT}/historical_incidents"



# BRONZE
BRONZE_ROOT = f"{LAKEHOUSE_ROOT}/bronze"

BRONZE_ORDERS = f"{BRONZE_ROOT}/orders"

BRONZE_DRIVERS = f"{BRONZE_ROOT}/drivers"

BRONZE_ROUTES = f"{BRONZE_ROOT}/routes"

BRONZE_ORDER_EVENTS = f"{BRONZE_ROOT}/order_events"

BRONZE_GPS = f"{BRONZE_ROOT}/gps"

BRONZE_WEATHER = f"{BRONZE_ROOT}/weather"

BRONZE_TRAFFIC = f"{BRONZE_ROOT}/traffic"



# SILVER
SILVER_ROOT = f"{LAKEHOUSE_ROOT}/silver"

SILVER_ORDERS = f"{SILVER_ROOT}/orders"

SILVER_DRIVERS = f"{SILVER_ROOT}/drivers"

SILVER_ROUTES = f"{SILVER_ROOT}/routes"

SILVER_ORDER_EVENTS = f"{SILVER_ROOT}/order_events"

SILVER_GPS = f"{SILVER_ROOT}/gps"

SILVER_WEATHER = f"{SILVER_ROOT}/weather"

SILVER_TRAFFIC = f"{SILVER_ROOT}/traffic"



# GOLD
GOLD_ROOT = f"{LAKEHOUSE_ROOT}/gold"

GOLD_SLA_RISK = f"{GOLD_ROOT}/sla_risk"

GOLD_DRIVER_PERFORMANCE = f"{GOLD_ROOT}/driver_performance"

GOLD_ZONE_PERFORMANCE = f"{GOLD_ROOT}/zone_performance"

GOLD_RECOMMENDATIONS = f"{GOLD_ROOT}/recommendations"