from pathlib import Path



# ROOT DEL PROYECTO LOCAL
PROJECT_ROOT = Path(__file__).resolve().parents[1]



# DATOS LOCALES
DATA_ROOT = PROJECT_ROOT / "data"

DATA_ADDRESS = DATA_ROOT / "reference"

DATA_GENERATED =  DATA_ROOT / "generated"


# LOCAL PROJECT
GENERATED_ORDERS = f"{DATA_GENERATED}/orders"

GENERATED_DRIVERS = f"{DATA_GENERATED}/drivers"

GENERATED_ROUTES = f"{DATA_GENERATED}/routes"

GENERATED_ORDER_EVENTS = f"{DATA_GENERATED}/order_events"

GENERATED_INCIDENT_EVENTS = f"{DATA_GENERATED}/incidents_events"

GENERATED_GPS = f"{DATA_GENERATED}/gps_events"

GENERATED_WEATHER = f"{DATA_GENERATED}/weather"

GENERATED_TRAFFIC = f"{DATA_GENERATED}/traffic"

GENERATED_HISTORICAL_ORDERS = f"{DATA_GENERATED}/historical_orders"

GENERATED_HISTORICAL_INCIDENTS = f"{DATA_GENERATED}/historical_incidents"


# CONFIGURACIÓN ONE LAKE 

WORKSPACE = "TFM_Logistic"
LAKEHOUSE_ROOT = "logistics_lakehouse.Lakehouse/Files"

# LANDING
LANDING_ROOT = f"{LAKEHOUSE_ROOT}/landing"

LANDING_ORDERS = f"{LANDING_ROOT}/orders"

LANDING_DRIVERS = f"{LANDING_ROOT}/drivers"

LANDING_ROUTES = f"{LANDING_ROOT}/routes"

LANDING_ORDER_EVENTS = f"{LANDING_ROOT}/order_events"

LANDING_INCIDENT_EVENTS = f"{LANDING_ROOT}/incidents_events"

LANDING_GPS = f"{LANDING_ROOT}/gps_events"

LANDING_WEATHER = f"{LANDING_ROOT}/weather"

LANDING_TRAFFIC = f"{LANDING_ROOT}/traffic"

LANDING_HISTORICAL_ORDERS = f"{LANDING_ROOT}/historical_orders"

LANDING_HISTORICAL_INCIDENTS = f"{LANDING_ROOT}/historical_incidents"